sbtc_contract = "SP2BJA4JYFJ7SDMNFJZ9TJ3GB80P9Z80ADPGK1C2F.sbtc-alpha"
mining_contract = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.main-contract-5-blocks.clar"
stacks_private_key = "753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601"
stacks_node_rpc_url = "http://localhost:20443"
bitcoin_node_rpc_url = "http://devnet:devnet@localhost:18443"
frost_dkg_round_id = 0
signer_config_path = ""
network_private_key = ""
network = "devnet"
transaction_fee = 2000
