http_relay_url = "http://localhost:9776"
keys_threshold = 4
frost_state_file = "frost.state.bin"
network_private_key = "6m3Cbx4wpdSChmUqR5P3WQyEfPPGQNjovZ4iPjQxCoN3"
signers =  [
    {public_key = "xvwd4f8L4oAmAXNhqMvQvbMiniCSeNH1rD9ZwCEEf7b6", key_ids = [1, 2]},
    {public_key = "cLuu4PSQLxi6bjFYGyTvyAFRUe3XfJL8mQ99Bd9A8mv9", key_ids = [3, 4]},
    {public_key = "gKCpZS42qdyVh9qQLtjbJYg8reEhjgyho6z6ghmLXZUx", key_ids = [5, 6]}
]
coordinator_public_key = "2A1tcY8RFby6pTNk8wQ3qGPCgWRXTL24yMwmcXiG7tKCZ"