[project]
name = 'sbtc-mini'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST000000000000000000002AMW42H.pox-3'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.clarity-bitcoin]
path = 'contracts/clarity-bitcoin.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin_test]
path = 'tests/clarity-bitcoin_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-btc-tx-helper]
path = 'contracts/sbtc-btc-tx-helper.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-controller]
path = 'contracts/sbtc-controller.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-controller_test]
path = 'tests/sbtc-controller_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-deposit-verifier]
path = 'contracts/sbtc-deposit-verifier.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-deposit-verifier_test]
path = 'tests/sbtc-deposit-verifier_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-registry]
path = 'contracts/sbtc-registry.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-registry_test]
path = 'tests/sbtc-registry_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-withdrawal-request-stx_test]
path = 'tests/sbtc-withdrawal-request-stx_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-withdrawal-verifier_test]
path = 'tests/sbtc-withdrawal-verifier_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-withdrawal-verifier]
path = 'contracts/sbtc-withdrawal-verifier.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-withdrawal-request-btc]
path = 'contracts/sbtc-withdrawal-request-btc.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-withdrawal-request-stx]
path = 'contracts/sbtc-withdrawal-request-stx.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-withdrawal-request-reclaim]
path = 'contracts/sbtc-withdrawal-request-reclaim.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-testnet-debug-controller]
path = 'contracts/sbtc-testnet-debug-controller.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-token_test]
path = 'tests/sbtc-token_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-wallet-vote]
path = 'contracts/sbtc-wallet-vote.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[contracts.pox-3]
path = 'contracts/pox-3.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-hand-off]
path = 'contracts/sbtc-hand-off.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-stacking-pool]
path = 'contracts/sbtc-stacking-pool.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-stacking-pool_test]
path = 'tests/sbtc-stacking-pool_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-stacking-pool_signer_test]
path = 'tests/sbtc-stacking-pool_signer_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-stacking-pool_as_protocol_test]
path = 'tests/sbtc-stacking-pool_as_protocol_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-stacking-pool_flow_test]
path = 'tests/sbtc-stacking-pool_flow_test.clar'
clarity_version = 2
epoch = 2.4


[contracts.sbtc-stacking-pool_allow_flow_test]
path = 'tests/sbtc-stacking-pool_allow_flow_test.clar'
clarity_version = 2
epoch = 2.4


[contracts.sbtc-stacking-pool_amonts_flow_test]
path = 'tests/sbtc-stacking-pool_amounts_flow_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-stacking-pool_inactive_flow_test]
path = 'tests/sbtc-stacking-pool_inactive_flow_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-stacking-pool_two_signers_flow_test]
path = 'tests/sbtc-stacking-pool_two_signers_flow_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-btc-tx-helper_test]
path = 'tests/sbtc-btc-tx-helper_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-hand-off_test]
path = 'tests/sbtc-hand-off_test.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
